apiVersion: v1
kind: Secret
metadata:
  name: postfacto-ext-postgresql
  namespace: default
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  username: bm1icnMlNDBwb3N0Z3Jlc3FsLW5tYi1wc2ZjLXN0YWc= # nmbrs%40postgresql-nmb-psfc-stag
  password: dGVzdDIwMjEq # test2021*
  host: cG9zdGdyZXNxbC1ubWItcHNmYy1zdGFnLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ== # postgresql-nmb-psfc-stag.postgres.database.azure.com
  database: cG9zdGZhY3RvLXN0YWdpbmctZGI= #  postfacto-staging-db