apiVersion: v1
kind: Secret
metadata:
  name: postfacto-ext-postgresql
  # namespace: default
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  username: ZmFrZS12YWx1ZQ==
  password: ZmFrZS12YWx1ZQ==
  host: ZmFrZS12YWx1ZQ==
  database: ZmFrZS12YWx1ZQ==

# This secret only will be deployed (created) when the helm chart
# is installed the first time (not in upgrade operations). This behavior
# is due to these two helm annotations used:
#
# helm.sh/hook: pre-install
# helm.sh/hook-delete-policy: before-hook-creation